### ISSUE TITLE
ProxyPref is "Null"

### ISSUE THREAD

**Issue by lectricas** [konmik/proxypref#2]
Hi. I've been using this library for a few days with dagger2 attached.
It worked fine. But as soon as I introduced Nucleous, proxyPref had broken.

Here is some code:

Proxy pref is built in NetModule:

```
@Module
public class NetModule {
    @Provides
    @Singleton
    FixedPreferences providesFixedPrefs(Application application) {
         return  ProxyPreferences
                .build(FixedPreferences.class, application.getSharedPreferences("fixedprefs", Context.MODE_PRIVATE));
    }
}
```

My interface:

```
public interface FixedPreferences {


    @DefaultString("a")
    String getAuthToken();
    void setAuthToken(String x);

    @DefaultLong(0l)
    Long getLastUploadUpdate();
    void setLastUploadUpdate(Long x);

    @DefaultLong(0l)
    Long getLastDownloadUpdate();
    void setLastDownloadUpdate(Long x);
}
```

I'm trying to inject it in BasePresenter:

```
public class BasePresenter<V extends NucleusAppCompatActivity> extends RxPresenter<V> {
    private static final String TAG = LogUtils.makeLogTag(BasePresenter.class.getSimpleName());
    @Inject
    FixedPreferences pref;
    @Inject
    FixedRecApi fixedRecApi; //this is a Retrofit Api. It works fine with dagger2 and Nucleous.
}
```

Then I extends BasePresenter by other presenters I have.
### Everything was fine untill I intorduced Nucleous

Also please take into account this debug window. It says that proxyPrefs are loaded, but unaccessable. 
![proxypref](https://cloud.githubusercontent.com/assets/8782219/13744452/3ec3fba2-ea01-11e5-94de-f6ad7cb3ab73.png)

**Comment by lectricas** [comment]
the solution was not related to proxy pref or nucleous. sorry

**Comment by lectricas** [comment]
this "null" in the name of prefs mislead me.

**Comment by konmik** [comment]
Hi,  yes,  it confuses me sometimes as well.  I think I need to implement 'toString'
