### ISSUE TITLE
Invalid shared preferences type while using with Kotlin

### ISSUE THREAD

**Issue by lectricas** [konmik/proxypref#3]
Hi, I know that proxyPref wants boxed types in getters and setters. 
Kotlin make ? sign to make primitive "boxed". 
https://discuss.kotlinlang.org/t/relationship-between-classes-like-kotlin-int-and-java-integer-and-int-primitive/671

I've made this trick and still getting this error.
Is this library compatible with Kotlin?

**Comment by konmik** [comment]
Hi, it should be compatible as I understand. 

But I'm not supporting this feature right now. 
If you want to push a fix that will make the library more friendly to Kotlin and not affect the standard Java usage, I'll merge it.

**Comment by lectricas** [comment]
I'm new in Kotlin so I'm not sure that I can handle it. But I'll try.  :)
