### ISSUE TITLE
Invalid shared preferences type: rx.Observable<java.lang.Boolean>

### ISSUE THREAD

**Issue by lectricas** [konmik/proxypref#4]
Hey! Can you please share some example of how to use observables with proxypref.
I want to wrap all my access to shared preferences in rx chain.

```
//    @DefaultBoolean(false)
//    @Preference(PREF_ENABLE_NOTIFICATION)
    Observable<Boolean> isNotificationEnabled();

//    @Preference(PREF_ENABLE_NOTIFICATION)
    Observable<Void> setNotificationEnabled(Boolean b);
```

I've tried to do this, but it gives me the error in the title.

**Comment by konmik** [comment]
I  have no idea. Could you elaborate?
